services:
  backend:
    build: ./vm-backend
    ports:
      - "8080:8080"
    env_file:
      - ./vm-backend/.env
    environment:
      PORT: "8080"
    networks:
      - vm-network

  frontend:
    build: ./vm-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_GRAPHQL_PROXY_URL: http://backend:8080
      VITE_AUTH_PROXY_URL: http://backend:8081
    depends_on:
      - backend
    networks:
      - vm-network

networks:
  vm-network:
