-- +goose Up
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linked_in TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS website TEXT;
