-- +goose Up
ALTER TABLE usage_log
  ADD COLUMN IF NOT EXISTS recraft_images_used BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_builds_used BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_exports_used BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_deployments_used BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_project_bytes BIGINT NOT NULL DEFAULT 0;
