import { useCallback, useState } from 'react';
import { Box, Button, Chip, CircularProgress, Typography, IconButton } from '@mui/material';
import { BookOpen, Palette, Sparkles, Type, Eye, Check, X, ChevronRight, ChevronLeft, Wand2, Download, DownloadCloud } from 'lucide-react';
import { AICreationStudio, type ProposedChange } from '../../components/venturemate/AICreationStudio';
import { NoBusinessSelected } from '../../components/venturemate/NoBusinessSelected';
import { useBusiness } from '../../contexts/BusinessContext';
import { graphqlRequest } from '../../lib/api';
import { PageHeader, StepWizard, GlassCard, AnimatedButton } from '../../components/shared';
import type { BrandKit, BrandingFull, LogoOption, ColorPalette, TypographyPair, ViewType } from '../../types/venturemate';

interface BrandingKitProps { onViewChange?: (_view: ViewType) => void; }

const DEFAULT_BRAND_KIT: BrandKit = {
  logo: '', logoWhite: '', logoIcon: '', primaryColor: '#10b981', secondaryColor: '#059669',
  accentColor: '#34d399', darkColor: '#052e24', fontHeading: 'Inter', fontBody: 'Inter', patterns: [], socialBanners: [],
};

function downloadSvg(svg: string, filename: string) {
  const blob = new Blob([svg], { type: 'image/svg+xml' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}

function downloadBrandKit(brand: BrandingFull, businessName: string) {
  const colors = [
    { label: 'Primary', value: brand.primaryColor },
    { label: 'Secondary', value: brand.secondaryColor },
    { label: 'Accent', value: brand.accentColor },
    { label: 'Dark', value: brand.darkColor },
  ];
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${businessName} Brand Kit</title>
<style>*{margin:0;padding:0;box-sizing:border-box}body{background:#0a0a0f;color:#fff;font-family:Inter,sans-serif;padding:48px}
h1{font-size:36px;font-weight:800;margin-bottom:4px}h2{font-size:18px;font-weight:700;margin-bottom:16px;color:#888}
.section{margin-bottom:40px}.logo-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:32px}
.logo-card{padding:32px;border-radius:12px;border:1px solid rgba(255,255,255,.1);text-align:center;min-height:140px;display:flex;flex-direction:column;align-items:center;justify-content:center}
.logo-label{font-size:11px;color:rgba(255,255,255,.4);margin-top:12px}.color-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}
.color-card{border-radius:10px;overflow:hidden;border:1px solid rgba(255,255,255,.08)}.color-swatch{height:60px}
.color-info{padding:10px}.color-name{font-size:10px;font-weight:700;text-transform:capitalize;color:#ccc}
.color-value{font-size:9px;font-family:monospace;color:#888;margin-top:2px}.typo-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}
.typo-card{padding:16px;border-radius:10px;border:1px solid rgba(255,255,255,.08)}.typo-label{font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:1px;color:#888;margin-bottom:6px}
.typo-name{font-size:20px;font-weight:700;color:#fff}.typo-sample{font-size:14px;color:#666;margin-top:4px}
</style></head><body>
<h1>${businessName}</h1>
<p style="color:#666;margin-bottom:40px;font-size:14px">Brand Identity Kit · Generated by VentureMate AI</p>
<div class="section"><h2>Logo</h2><div class="logo-grid">
${['logo.png', 'logo-white.png', 'logo-icon.png'].map((f, i) => {
  const svg = i === 0 ? brand.logo : i === 1 ? brand.logoWhite : brand.logoIcon;
  if (!svg) return '';
  const clean = svg.includes('<svg') ? svg : atob(svg.split(',')[1] || '');
  return `<div class="logo-card" style="background:${i === 1 ? brand.darkColor : '#ffffff'}"><div style="max-width:100px">${clean}</div><div class="logo-label">${['On Light', 'On Dark', 'Icon'][i]}</div></div>`;
}).join('')}
</div></div>
<div class="section"><h2>Colour Palette</h2><div class="color-grid">
${colors.map(c => `<div class="color-card"><div class="color-swatch" style="background:${c.value}"></div><div class="color-info"><div class="color-name">${c.label}</div><div class="color-value">${c.value}</div></div></div>`).join('')}
</div></div>
<div class="section"><h2>Typography</h2><div class="typo-grid">
<div class="typo-card"><div class="typo-label">Heading Font</div><div class="typo-name" style="font-family:${brand.fontHeading}">${brand.fontHeading}</div><div class="typo-sample" style="font-family:${brand.fontHeading}">Aa Bb Cc 0123456789</div></div>
<div class="typo-card"><div class="typo-label">Body Font</div><div class="typo-name" style="font-family:${brand.fontBody}">${brand.fontBody}</div><div class="typo-sample" style="font-family:${brand.fontBody}">Aa Bb Cc 0123456789</div></div>
</div></div>
<p style="margin-top:48px;font-size:11px;color:#444;text-align:center">Generated by VentureMate · venturemate.net</p>
</body></html>`;
  const blob = new Blob([html], { type: 'text/html' });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `${businessName.replace(/[^a-zA-Z0-9]/g, '_')}_BrandKit.html`;
  a.click();
  URL.revokeObjectURL(a.href);
}

function isLightColor(hex: string): boolean {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return (0.299 * r + 0.587 * g + 0.114 * b) > 160;
}

function adaptColor(match: string, attr: string, onDark: boolean): string {
  const color = match.replace(`${attr}="`, '').replace('"', '');
  if (!/^#[0-9A-Fa-f]{6}$/.test(color)) return match;
  const light = isLightColor(color);
  return onDark ? (light ? match : `${attr}="rgba(255,255,255,.85)"`) : (light ? `${attr}="rgba(0,0,0,.75)"` : match);
}

function renderSvg(svg: string, options?: { dark?: boolean; size?: number }) {
  try {
    let cleaned = svg.startsWith('data:') ? atob(svg.split(',')[1]?.replace(/-/g, '+').replace(/_/g, '/') || '') : svg;
    const onDark = options?.dark === true;
    cleaned = cleaned.replace(/(fill=")(?:none|transparent)(")/gi, '___KEEP_FILL___$1$2___END_KEEP___');
    cleaned = cleaned.replace(/fill="#[0-9A-Fa-f]{6}"/gi, (m) => adaptColor(m, 'fill', onDark));
    cleaned = cleaned.replace(/stroke="#[0-9A-Fa-f]{6}"/gi, (m) => adaptColor(m, 'stroke', onDark));
    cleaned = cleaned.replace(/<text[^>]*fill="#[0-9A-Fa-f]{6}"/gi, (m) => {
      const color = m.match(/fill="#([0-9A-Fa-f]{6})"/i);
      if (!color) return m;
      const light = isLightColor('#' + color[1]);
      return onDark ? (light ? m : m.replace(/fill="#[0-9A-Fa-f]{6}"/i, 'fill="rgba(255,255,255,.9)"')) : (light ? m.replace(/fill="#[0-9A-Fa-f]{6}"/i, 'fill="rgba(0,0,0,.8)"') : m);
    });
    cleaned = cleaned.replace(/___KEEP_FILL___fill="(?:none|transparent)"___END_KEEP___/g, 'fill="none"');
    const sz = options?.size || 100;
    return <Box sx={{ display: 'flex', '& svg': { width: sz, height: sz, maxWidth: sz, maxHeight: sz } }} dangerouslySetInnerHTML={{ __html: cleaned }} />;
  } catch { return null; }
}

function ColorSwatch({ label, value, gradient, onClick }: { label: string; value: string; gradient?: string; onClick?: () => void }) {
  const [copied, setCopied] = useState(false);
  return (
    <Box sx={{
      borderRadius: 2, overflow: 'hidden', border: '1px solid rgba(255,255,255,.08)',
      cursor: 'pointer', transition: 'all .2s', '&:hover': onClick ? { transform: 'translateY(-2px)', borderColor: 'var(--vm-primary-500)' } : {},
    }} onClick={() => { if (onClick) return onClick(); navigator.clipboard.writeText(value); setCopied(true); setTimeout(() => setCopied(false), 1500); }}>
      <Box sx={{ height: { xs: 44, sm: 52 }, background: gradient || value }} />
      <Box sx={{ px: 1.25, py: 0.75 }}>
        <Typography sx={{ color: 'var(--vm-text-primary)', fontSize: 10, fontWeight: 700, textTransform: 'capitalize' }}>{label}</Typography>
        <Typography sx={{ color: copied ? '#22c55e' : 'var(--vm-text-muted)', fontSize: 9, fontFamily: 'monospace' }}>{copied ? 'Copied!' : value}</Typography>
      </Box>
    </Box>
  );
}

function FontPreview({ name, label }: { name: string; label: string }) {
  if (!name) return null;
  return (
    <GlassCard sx={{ flex: 1, p: 1.5 }} hover={false}>
      <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 9, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1, mb: 0.5 }}>{label}</Typography>
      <Typography sx={{ fontFamily: name, fontSize: 16, fontWeight: 700, color: 'var(--vm-text-primary)' }}>{name}</Typography>
      <Typography sx={{ fontFamily: name, fontSize: 11, color: 'var(--vm-text-muted)', mt: 0.25, opacity: 0.7 }}>Aa Bb Cc Dd Ee Ff Gg 0123456789</Typography>
    </GlassCard>
  );
}

function ColorPickerStep({ palettes, selected, onSelect }: { palettes: ColorPalette[]; selected: number; onSelect: (i: number) => void }) {
  return (
    <Box>
      <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 2 }}>Choose a colour palette</Typography>
      <Box sx={{ display: 'flex', gap: 1.5, flexDirection: { xs: 'column', sm: 'row' } }}>
        {palettes.map((pal, i) => {
          const c = pal.colors;
          const isSelected = i === selected;
          return (
            <GlassCard key={i} onClick={() => onSelect(i)} hover={false} sx={{
              flex: 1, p: 1.5, cursor: 'pointer',
              border: isSelected ? `2px solid ${c.primary}` : '1px solid var(--vm-border-subtle)',
              bgcolor: isSelected ? `${c.primary}08` : undefined,
              transition: 'all .2s', '&:hover': { transform: 'translateY(-3px)', boxShadow: `0 8px 24px ${c.primary}20` },
            }}>
              <Box sx={{ display: 'flex', gap: 0.5, mb: 1 }}>
                {[c.primary, c.secondary, c.accent, c.background, c.text].map((h, j) => (
                  <Box key={j} sx={{ flex: 1, height: { xs: 28, sm: 36 }, borderRadius: 1, bgcolor: h, border: h === '#ffffff' || h === c.background ? '1px solid rgba(255,255,255,.1)' : 'none' }} />
                ))}
              </Box>
              <Typography sx={{ fontSize: 13, fontWeight: 700, color: 'var(--vm-text-primary)' }}>{pal.name}</Typography>
              <Typography sx={{ fontSize: 10, color: 'var(--vm-text-muted)', mt: 0.25, lineHeight: 1.5 }}>{pal.rationale?.slice(0, 80)}</Typography>
            </GlassCard>
          );
        })}
      </Box>
    </Box>
  );
}

function TypoPickerStep({ pairs, selected, onSelect }: { pairs: TypographyPair[]; selected: number; onSelect: (i: number) => void }) {
  return (
    <Box>
      <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 2 }}>Choose typography</Typography>
      <Box sx={{ display: 'flex', gap: 1.5, flexDirection: { xs: 'column', sm: 'row' } }}>
        {pairs.map((pair, i) => {
          const isSelected = i === selected;
          return (
            <GlassCard key={i} onClick={() => onSelect(i)} hover={false} sx={{
              flex: 1, p: 2, cursor: 'pointer',
              border: isSelected ? '2px solid var(--vm-primary-500)' : '1px solid var(--vm-border-subtle)',
              bgcolor: isSelected ? 'var(--vm-primary-700)10' : undefined,
              '&:hover': { transform: 'translateY(-3px)' },
            }}>
              <Box sx={{ mb: 1.5 }}>
                <Typography sx={{ fontFamily: pair.primaryFont, fontSize: 22, fontWeight: 800, color: 'var(--vm-text-primary)', lineHeight: 1.1 }}>{pair.primaryFont}</Typography>
                <Typography sx={{ fontFamily: pair.secondaryFont, fontSize: 14, color: 'var(--vm-text-muted)', mt: 0.5 }}>{pair.secondaryFont}</Typography>
              </Box>
              <Typography sx={{ fontSize: 11, color: 'var(--vm-text-secondary)', fontFamily: pair.secondaryFont, lineHeight: 1.6 }}>{pair.rationale?.slice(0, 100)}</Typography>
            </GlassCard>
          );
        })}
      </Box>
    </Box>
  );
}

function LogoPickerStep({ logos, selected, onSelect }: { logos: LogoOption[]; selected: number; onSelect: (i: number) => void }) {
  return (
    <Box>
      <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 2 }}>Choose a logo</Typography>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' }, gap: 1.5 }}>
        {logos.map((logo, i) => {
          const isSelected = i === selected;
          return (
            <GlassCard key={i} hover={false} sx={{
              p: 2, textAlign: 'center',
              border: isSelected ? '2px solid var(--vm-primary-500)' : '1px solid var(--vm-border-subtle)',
              bgcolor: isSelected ? 'var(--vm-primary-700)15' : undefined,
              '&:hover': { transform: 'translateY(-3px)' },
            }}>
              <Box sx={{ cursor: 'pointer' }} onClick={() => onSelect(i)}>
                <Box sx={{ height: 90, display: 'flex', alignItems: 'center', justifyContent: 'center', mb: 1 }}>
                  {renderSvg(logo.svg, { size: 72 })}
                </Box>
                <Typography sx={{ fontSize: 12, fontWeight: 700, color: 'var(--vm-text-primary)' }}>{logo.name}</Typography>
                <Chip size="small" label={logo.type} sx={{ mt: 0.5, fontSize: 9, textTransform: 'capitalize' }} />
                <Typography sx={{ fontSize: 10, color: 'var(--vm-text-muted)', mt: 0.75, lineHeight: 1.5 }}>{logo.concept?.slice(0, 80)}</Typography>
              </Box>
              <IconButton size="small" onClick={() => downloadSvg(logo.svg, `${logo.name.replace(/[^a-zA-Z0-9]/g, '_')}.svg`)} sx={{ mt: 1, color: 'var(--vm-text-muted)', '&:hover': { color: 'var(--vm-primary-400)' } }}>
                <Download size={14} />
              </IconButton>
            </GlassCard>
          );
        })}
      </Box>
    </Box>
  );
}

function VariationsDisplay({ logo, darkColor }: { logo: LogoOption; darkColor: string }) {
  const items: { label: string; svg: string; bg: string; dark: boolean }[] = [
    { label: 'Light BG', svg: logo.variations?.lightBackground || logo.svg, bg: '#ffffff', dark: false },
    { label: 'Dark BG', svg: logo.variations?.darkBackground || logo.svg, bg: darkColor || '#0f172a', dark: true },
    { label: 'Monochrome', svg: logo.variations?.monochrome || logo.svg, bg: '#f8fafc', dark: false },
  ];
  return (
    <Box>
      <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 2 }}>Logo Variations</Typography>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(3, 1fr)' }, gap: 1 }}>
        {items.map((item) => (
          <Box key={item.label} sx={{
            p: 2, borderRadius: 2, bgcolor: item.bg, border: '1px solid rgba(255,255,255,.08)',
            textAlign: 'center', minHeight: 100, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
            position: 'relative',
          }}>
            {renderSvg(item.svg, { dark: item.dark, size: 72 })}
            <Typography sx={{ fontSize: 9, color: item.dark ? 'rgba(255,255,255,.5)' : 'rgba(0,0,0,.4)', mt: 0.75 }}>{item.label}</Typography>
            <IconButton size="small" onClick={() => downloadSvg(item.svg, `${logo.name.replace(/[^a-zA-Z0-9]/g, '_')}_${item.label.replace(/ /g, '_').toLowerCase()}.svg`)}
              sx={{ position: 'absolute', top: 4, right: 4, color: item.dark ? 'rgba(255,255,255,.3)' : 'rgba(0,0,0,.3)', '&:hover': { color: item.dark ? 'white' : 'black' } }}>
              <Download size={12} />
            </IconButton>
          </Box>
        ))}
      </Box>
    </Box>
  );
}

function BrandPreview({ brand, businessName, proposed = false }: { brand: BrandingFull; businessName: string; proposed?: boolean }) {
  const { primaryColor, secondaryColor, accentColor, darkColor, fontHeading, fontBody } = brand;
  const gradient = `linear-gradient(135deg, ${darkColor}, ${primaryColor})`;
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5 }}>
      <GlassCard sx={{
        p: { xs: 2.5, sm: 3.5 },
        background: gradient,
        border: proposed ? '1px solid var(--vm-primary-500)' : '1px solid rgba(255,255,255,.08)',
      }}>
        {!proposed && (
          <IconButton onClick={() => downloadBrandKit(brand as BrandingFull, businessName)}
            sx={{ position: 'absolute', top: 12, right: 12, zIndex: 2, bgcolor: 'rgba(255,255,255,.08)', backdropFilter: 'blur(8px)', color: 'rgba(255,255,255,.6)', '&:hover': { bgcolor: 'rgba(255,255,255,.15)', color: 'white' } }}>
            <DownloadCloud size={18} />
          </IconButton>
        )}
        <Box sx={{ position: 'absolute', top: -40, right: -40, width: 160, height: 160, borderRadius: '50%', background: `radial-gradient(circle, ${accentColor}30, transparent 70%)` }} />
        <Box sx={{ position: 'absolute', bottom: -20, left: -20, width: 100, height: 100, borderRadius: '50%', background: `radial-gradient(circle, ${primaryColor}40, transparent 70%)` }} />
        <Box sx={{ position: 'relative', zIndex: 1, display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '120px 1fr' }, gap: 2.5, alignItems: 'center' }}>
          <Box sx={{
            width: { xs: 96, sm: 120 }, height: { xs: 96, sm: 120 }, borderRadius: 2.5,
            bgcolor: 'rgba(255,255,255,.08)', backdropFilter: 'blur(10px)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            mx: { xs: 'auto', sm: 0 }, border: '1px solid rgba(255,255,255,.1)',
            position: 'relative',
          }}>
            {brand.logo ? (
              brand.logo.includes('<svg') || brand.logo.startsWith('data:') ? renderSvg(brand.logo, { dark: true, size: 80 }) :
              <Box component="img" src={brand.logo} sx={{ maxWidth: 80, maxHeight: 80, objectFit: 'contain' }} />
            ) : <Sparkles size={36} color="rgba(255,255,255,.3)" />}
            {brand.logo && brand.logo.includes('<svg') && (
              <IconButton size="small" onClick={() => downloadSvg(brand.logo, `${businessName.replace(/[^a-zA-Z0-9]/g, '_')}_logo.svg`)}
                sx={{ position: 'absolute', bottom: -8, right: -8, bgcolor: 'rgba(0,0,0,.5)', color: 'white', width: 24, height: 24, '&:hover': { bgcolor: 'rgba(0,0,0,.7)' } }}>
                <Download size={12} />
              </IconButton>
            )}
          </Box>
          <Box sx={{ textAlign: { xs: 'center', sm: 'left' } }}>
            <Typography sx={{ color: 'white', fontFamily: fontHeading, fontSize: { xs: 22, sm: 30 }, fontWeight: 900, lineHeight: 1.1 }}>{businessName}</Typography>
            <Typography sx={{ color: 'rgba(255,255,255,.65)', fontFamily: fontBody, fontSize: 12, mt: 0.75, lineHeight: 1.6, maxWidth: 400 }}>
              {brand.logoConcept || 'AI-crafted brand identity.'}
            </Typography>
          </Box>
        </Box>
      </GlassCard>
      <Box>
        <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 1, display: 'flex', alignItems: 'center', gap: 0.75 }}><Palette size={14} /> Colours</Typography>
        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,1fr)', sm: 'repeat(4,1fr)' }, gap: 1 }}>
          <ColorSwatch label="Primary" value={primaryColor} gradient={`linear-gradient(135deg, ${primaryColor}, ${accentColor})`} />
          <ColorSwatch label="Secondary" value={secondaryColor} />
          <ColorSwatch label="Accent" value={accentColor} />
          <ColorSwatch label="Dark" value={darkColor} />
        </Box>
      </Box>
      <Box>
        <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 1, display: 'flex', alignItems: 'center', gap: 0.75 }}><Type size={14} /> Typography</Typography>
        <Box sx={{ display: 'flex', gap: 1, flexDirection: { xs: 'column', sm: 'row' } }}>
          <FontPreview name={fontHeading || 'Inter'} label="Heading" />
          <FontPreview name={fontBody || 'Inter'} label="Body" />
        </Box>
      </Box>
      {brand.logo && (
        <Box>
          <Typography sx={{ color: 'var(--vm-text-muted)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 1, mb: 1, display: 'flex', alignItems: 'center', gap: 0.75 }}><Eye size={14} /> Variations</Typography>
          <Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,1fr)', sm: 'repeat(3,1fr)' }, gap: 1 }}>
            {[
              { label: 'Light', bg: '#ffffff', dark: false },
              { label: 'Dark', bg: darkColor, dark: true },
              { label: 'Gradient', bg: gradient, dark: true },
            ].map(({ label, bg, dark }) => (
              <Box key={label} sx={{ p: 2, borderRadius: 2, bgcolor: bg, border: '1px solid rgba(255,255,255,.08)', textAlign: 'center', minHeight: 80, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                {renderSvg(brand.logo, { dark, size: 64 })}
                <Typography sx={{ fontSize: 9, color: dark ? 'rgba(255,255,255,.5)' : 'rgba(0,0,0,.4)', mt: 0.75 }}>{label}</Typography>
              </Box>
            ))}
          </Box>
        </Box>
      )}
    </Box>
  );
}

const BRAND_GUIDE_QUERY = `mutation GenGuide($businessId: ID!) { generateBrandGuide(businessId: $businessId) { id title content order } }`;
interface BrandGuideSection { id: string; title: string; content: string; order: number; }

export function BrandingKitPage(_props: BrandingKitProps) {
  const { selectedBusiness } = useBusiness();
  const [guideSections, setGuideSections] = useState<BrandGuideSection[] | null>(null);
  const [guideLoading, setGuideLoading] = useState(false);
  const [step, setStep] = useState<'colors' | 'typography' | 'logos' | 'variations' | 'complete'>('colors');
  const [proposedBrand, setProposedBrand] = useState<BrandingFull | null>(null);
  const [selectedColorIdx, setSelectedColorIdx] = useState(0);
  const [selectedTypoIdx, setSelectedTypoIdx] = useState(0);
  const [selectedLogoIdx, setSelectedLogoIdx] = useState(0);

  const handleGenerateGuide = useCallback(async () => {
    if (!selectedBusiness) return;
    setGuideLoading(true);
    try {
      const data = await graphqlRequest<{ generateBrandGuide: BrandGuideSection[] }>(BRAND_GUIDE_QUERY, { businessId: selectedBusiness.id });
      setGuideSections(data.generateBrandGuide);
    } catch { /* ignore */ } finally { setGuideLoading(false); }
  }, [selectedBusiness]);

  if (!selectedBusiness) return <NoBusinessSelected message="Select a business to create its identity with AI." />;

  const brand = { ...DEFAULT_BRAND_KIT, ...(selectedBusiness.brandKit || {}) } as BrandingFull;
  const hasApprovedBrand = Boolean(brand.logo);
  const fullBrand = proposedBrand || brand;
  const logos = fullBrand.logos || [];
  const palettes = fullBrand.colors || [];
  const typoPairs = fullBrand.typography || [];
  const stepKeys: (typeof step)[] = ['colors', 'typography', 'logos', 'variations'];
  const currentStepIdx = stepKeys.indexOf(step);

  const advanceStep = () => {
    const next = currentStepIdx + 1;
    if (next < stepKeys.length) setStep(stepKeys[next]);
    else setStep('complete');
  };

  return (
    <Box sx={{ p: { xs: 1.25, sm: 2, md: 3 } }}>
      <PageHeader
        icon={<Palette size={18} />}
        title="Branding Kit"
        subtitle="AI-crafted brand identity with multi-step wizard"
        businessName={selectedBusiness.name}
        chips={hasApprovedBrand ? (
          <Button size="small" variant="outlined" startIcon={guideLoading ? <CircularProgress size={13} /> : <BookOpen size={13} />} disabled={guideLoading} onClick={handleGenerateGuide} sx={{ textTransform: 'none', fontSize: 11 }}>
            {guideLoading ? 'Generating…' : 'Brand Guide'}
          </Button>
        ) : undefined}
      />

      {/* Step indicator */}
      {hasApprovedBrand && (
        <StepWizard
          steps={[
            { label: 'Colours', icon: <Palette size={12} /> },
            { label: 'Typography', icon: <Type size={12} /> },
            { label: 'Logo', icon: <Eye size={12} /> },
            { label: 'Variations', icon: <Wand2 size={12} /> },
          ]}
          currentStep={currentStepIdx}
          onBack={currentStepIdx > 0 ? () => setStep(stepKeys[currentStepIdx - 1]) : undefined}
          onNext={currentStepIdx < stepKeys.length - 1 ? advanceStep : undefined}
          showNav={false}
        />
      )}

      {guideSections && (
        <GlassCard sx={{ mb: 2.5 }}>
          <Box sx={{ px: 2, py: 1.5, borderBottom: '1px solid rgba(255,255,255,.06)', display: 'flex', alignItems: 'center', gap: 1 }}>
            <BookOpen size={16} />
            <Typography sx={{ fontSize: 13, fontWeight: 700, flex: 1 }}>Brand Identity Guide</Typography>
            <Button size="small" sx={{ textTransform: 'none', fontSize: 11 }} onClick={() => {
              const html = guideSections.sort((a, b) => a.order - b.order).map(s => s.content).join('');
              const w = window.open('', '_blank');
              if (w) { w.document.write(html); w.document.close(); }
            }}>Open Full Guide</Button>
            <IconButton size="small" onClick={() => setGuideSections(null)} sx={{ color: 'var(--vm-text-muted)' }}><X size={14} /></IconButton>
          </Box>
          {guideSections.sort((a, b) => a.order - b.order).map(s => (
            <Box key={s.id} sx={{ '& > *': { maxWidth: '100%' } }} dangerouslySetInnerHTML={{ __html: s.content }} />
          ))}
        </GlassCard>
      )}

      {/* Main content */}
      {!hasApprovedBrand && !proposedBrand ? (
        <AICreationStudio
          domain="branding" title="" description=""
          placeholder="Describe the brand feel you want (e.g., 'Modern, trustworthy edtech brand with green tones')"
          starterPrompts={[
            'Generate a complete brand identity from my business details.',
            'Create a premium luxury brand feel.',
            'Make it warm, friendly and approachable.',
            'Design a bold tech-forward identity.',
          ]}
          emptyLabel="Generate your first brand identity to get started."
          renderCurrent={() => null}
          renderProposal={(change: ProposedChange) => {
            const parsed = (() => { try { return JSON.parse(change.newValue) as BrandingFull; } catch { return null; } })();
            if (!parsed) return <Typography color="error">Invalid proposal</Typography>;
            setProposedBrand(parsed);
            return <BrandPreview brand={{ ...DEFAULT_BRAND_KIT, ...parsed }} businessName={selectedBusiness.name} proposed />;
          }}
          onApproved={() => { setStep('colors'); window.location.reload(); }}
        />
      ) : (
        <Box>
          {(hasApprovedBrand || proposedBrand) && palettes.length > 0 && step === 'colors' && (
            <GlassCard sx={{ p: 2.5, mb: 2 }}>
              <ColorPickerStep palettes={palettes} selected={selectedColorIdx} onSelect={setSelectedColorIdx} />
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'flex-end' }}>
                <AnimatedButton variant="primary" size="sm" icon={<ChevronRight size={14} />} onClick={advanceStep}>Next: Typography</AnimatedButton>
              </Box>
            </GlassCard>
          )}
          {typoPairs.length > 0 && step === 'typography' && (
            <GlassCard sx={{ p: 2.5, mb: 2 }}>
              <TypoPickerStep pairs={typoPairs} selected={selectedTypoIdx} onSelect={setSelectedTypoIdx} />
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'space-between' }}>
                <AnimatedButton variant="ghost" size="sm" icon={<ChevronLeft size={14} />} onClick={() => setStep('colors')}>Back</AnimatedButton>
                <AnimatedButton variant="primary" size="sm" icon={<ChevronRight size={14} />} onClick={advanceStep}>Next: Logo</AnimatedButton>
              </Box>
            </GlassCard>
          )}
          {logos.length > 0 && step === 'logos' && (
            <GlassCard sx={{ p: 2.5, mb: 2 }}>
              <LogoPickerStep logos={logos} selected={selectedLogoIdx} onSelect={setSelectedLogoIdx} />
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'space-between' }}>
                <AnimatedButton variant="ghost" size="sm" icon={<ChevronLeft size={14} />} onClick={() => setStep('typography')}>Back</AnimatedButton>
                <AnimatedButton variant="primary" size="sm" icon={<ChevronRight size={14} />} onClick={advanceStep}>Next: Variations</AnimatedButton>
              </Box>
            </GlassCard>
          )}
          {logos.length > 0 && step === 'variations' && (
            <GlassCard sx={{ p: 2.5, mb: 2 }}>
              <VariationsDisplay logo={logos[selectedLogoIdx]} darkColor={fullBrand.darkColor} />
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'space-between' }}>
                <AnimatedButton variant="ghost" size="sm" icon={<ChevronLeft size={14} />} onClick={() => setStep('logos')}>Back</AnimatedButton>
                <AnimatedButton variant="success" size="sm" icon={<Check size={14} />} onClick={() => setStep('complete')}>Complete Brand</AnimatedButton>
              </Box>
            </GlassCard>
          )}
          {(hasApprovedBrand && step === 'complete') && (
            <AICreationStudio
              domain="branding" title="" description=""
              placeholder="Tell AI what to revise in your brand identity…"
              starterPrompts={['Create a more premium and minimal logo option.', 'Keep my colours but redesign the logo mark.', 'Make the identity warmer and friendlier.']}
              emptyLabel=""
              renderCurrent={() => <BrandPreview brand={brand} businessName={selectedBusiness.name} />}
              renderProposal={(change: ProposedChange) => {
                const parsed = (() => { try { return JSON.parse(change.newValue) as BrandingFull; } catch { return null; } })();
                return parsed ? <BrandPreview brand={{ ...DEFAULT_BRAND_KIT, ...parsed }} businessName={selectedBusiness.name} proposed /> : <Typography color="error">Invalid proposal</Typography>;
              }}
            />
          )}
        </Box>
      )}
    </Box>
  );
}
